development:
  type: pop
  server: mail.you.com
  username: you
  password: password
  
test:
  type: pop
  server: localhost
  username: username
  password: password
  
production:
  type: pop
  server: localhost
  username: username
  password: password
