#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/environment.rb'

class MailerDaemonFetcherDaemon < Daemon::Base
  
  @config = YAML.load_file("#{RAILS_ROOT}/config/mailer_daemon.yml")
  @config = @config[RAILS_ENV].to_options
  
  @sleep_time = @config.delete(:sleep_time) || 60
    @fetcher = Fetcher.create({:receiver => MessageMailer}.merge(@config))
  
  def self.start
    puts "Starting MailerDaemonFetcherDaemon"
    @fetcher = Fetcher.create({:receiver => MessageMailer}.merge(@config))

    loop do
      @fetcher.fetch
      sleep(@sleep_time)
    end
  end
  
  def self.stop
    puts "Stopping MailerDaemonFetcherDaemon"
  end
  
end

MailerDaemonFetcherDaemon.daemonize
